# -*- coding: utf-8 -*-
"""ImageClassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PJp5EhK6FUXjC8IzlHqTd-tt1t2p6gRt
"""

import numpy as np

import torch
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader

transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

# Donwload and load the training dataset
train_dataset = torchvision.datasets.CIFAR10(
    root = './data',
    train = True,
    download = True,
    transform = transform
)

test_dataset = torchvision.datasets.CIFAR10(
    root = './data',
    train = False,
    download = True,
    transform = transform
)

x_train = train_dataset.data.reshape( 50000, -1).astype(np.float32)
y_train = np.array(train_dataset.targets)


x_test = test_dataset.data.reshape( 10000, -1).astype(np.float32)
y_test = np.array(test_dataset.targets)

# Subset — full dataset is very large and slow
X_tr = x_train[:5000]
y_tr = y_train[:5000]
X_te = x_test[:500]
y_te = y_test[:500]

class NearestNeighbour(object):
    def __init__(self):
        pass

    def train(self, x, y):
        # remembering the training data
        # dimension of x is NxD and y is Nx1
        self.Xtr = x
        self.Ytr = y

    def predict(self, x):
        # x is NxD such that each row is what we wish to predict label for
        num_te = x.shape[0]
        # pre-populating prediction with zeros
        Ypred = np.zeros(num_te, dtype= self.Ytr.dtype)

        # all test rows i.e all test examples
        for i in range(num_te):
            distances = np.sum( np.abs( self.Xtr - x[i, :] ) , axis = 1 )
            min_ix = np.argmin(distances)
            Ypred[i] = self.Ytr[min_ix]    # predict label of nearest example

        return Ypred

nn = NearestNeighbour()
nn.train(X_tr, y_tr)
y_pred = nn.predict(X_te)

accuracy = np.mean(y_pred == y_te)
print(f"Accuracy: {accuracy: .4f}")

class NearestNeighbour_L2(object):
    def __init__(self):
        pass

    def train(self, x, y):
        # remembering the training data
        # dimension of x is NxD and y is Nx1
        self.Xtr = x
        self.Ytr = y

    def predict(self, x):
        # x is NxD such that each row is what we wish to predict label for
        num_te = x.shape[0]
        # pre-populating prediction with zeros
        Ypred = np.zeros(num_te, dtype= self.Ytr.dtype)

        # all test rows i.e all test examples
        for i in range(num_te):
            distances = np.sqrt(np.sum(np.square(self.Xtr - x[i,:]), axis = 1))
            min_ix = np.argmin(distances)
            Ypred[i] = self.Ytr[min_ix]    # predict label of nearest example

        return Ypred

nn_L2 = NearestNeighbour_L2()
nn_L2.train(X_tr, y_tr)
y_pred_L2 = nn_L2.predict(X_te)

accuracy_L2 = np.mean(y_pred_L2 == y_te)
print(f"Accuracy_L2: {accuracy_L2: .4f}")